# <center> Assignment

## Cramer's rule

## 1. solve the following systems of linear equations using cramer's rule.

$(a)2x_1-x_2+x_3=-3, x_1+x_2-3x_3=17, 5x_1-2x_2-4x_3=20$

$(b)2x1+3x2-x3=4, x1+4x2+x3=-1, 5x1-x2+2x3=1$

$(c)-x1+2x2+4x3-2x4+3x5=24,    20x1+5x2+3x3-2x4-x5=29,   2x1+18x2+60x3+5x4-3x5=177,   2x1+4x2+4x3+3x5=26$

$(d)2x1+3x2-x3=4,   x1+4x2+x3=-1,   5x1-x2-+2x3=1,    2x1+3x2-6x3+5x4+4x5=0$



## lets create the function whichh solve the system of equation using the cramer's rule

In [27]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [28]:
import numpy as np
import scipy.linalg as la 

In [29]:
mat=np.array([[4,12,-16],[12,37,-43],[-16,-43,98]])
print(np.linalg.cholesky(mat))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


# Solving system of linear equations

In [30]:
A=np.array([[2,-1,3],[1,2,-3],[5,-2,-4]])
b=np.array([-3,17,20])
x=np.linalg.solve(A,b)
x


array([ 3.54716981,  3.35849057, -2.24528302])

In [31]:
A=np.array([[2,-1,3],[1,2,-3],[5,-2,-4]])
b=np.array([-3,17,20])

In [32]:
def cramer(A,b):
    d=np.linalg.det(A)
    if(d!=0):
        row,col=A.shape
        x=[]
        for i in range(col):
            c=A.copy()
            c[:,i]=b
            v=np.linalg.det(c)/np.linalg.det(A)
            x.append(round(v))
        print("The system of linear equation is :")
        print(x)
    else: 
        print("The system has no solution :")



In [33]:
cramer(A,b)

The system of linear equation is :
[4, 3, -2]


# set of vectors

In [34]:
A=np.array([[1,0,1],[1,1,0],[0,2,1]])
print(A)

[[1 0 1]
 [1 1 0]
 [0 2 1]]


In [35]:
for i in range(A.shape[0]):
    for j in range(A.shape[0]):
        if i != j:
            inner_product=np.inner( A[:,i], A[:,j] )
            norm_i = np.linalg.norm(A[:,i])
            norm_j = np.linalg.norm(A[:,j])
            print('I: ', A[:,i])
            print('J: ', A[:,j])
            print('Prod: ',inner_product)
            print('Norm i: ' , norm_i)
            print('Norm j: ' , norm_j)
            if np.abs(inner_product - norm_j * norm_i) < 1E-5:
                print('Dependent')
            else:print('Independent')

I:  [1 1 0]
J:  [0 1 2]
Prod:  1
Norm i:  1.4142135623730951
Norm j:  2.23606797749979
Independent
I:  [1 1 0]
J:  [1 0 1]
Prod:  1
Norm i:  1.4142135623730951
Norm j:  1.4142135623730951
Independent
I:  [0 1 2]
J:  [1 1 0]
Prod:  1
Norm i:  2.23606797749979
Norm j:  1.4142135623730951
Independent
I:  [0 1 2]
J:  [1 0 1]
Prod:  2
Norm i:  2.23606797749979
Norm j:  1.4142135623730951
Independent
I:  [1 0 1]
J:  [1 1 0]
Prod:  1
Norm i:  1.4142135623730951
Norm j:  1.4142135623730951
Independent
I:  [1 0 1]
J:  [0 1 2]
Prod:  2
Norm i:  1.4142135623730951
Norm j:  2.23606797749979
Independent


# Properties of matrix

In [36]:
def properties(A):
    row,col=A.shape
    print("The given Matrix is \n",A)
    print("The Determinant of The Matrix is ",round(np.linalg.det(A)))
    print("The Rank of the Matrix is: ",np.linalg.matrix_rank(A))
    if row==col:
        print("The given Matrix is Square Matrix")
    else:
        print("The given Matrix is not Square Matrix")
    if (A.T==A).all():
        print("The given Matrix is Symmetric Matrix")
    else:
        print("The given Matrix is not Symmetric Matrix")
    if (np.linalg.det(A)!=0).all():
        print("The given Matrix is singular  Matrix")
    else:
        print("The given Matrix is Not singular  Matrix")
    if (np.linalg.inv(A)==A.T).all():
        print("The given Matrix is orthogonal Matrix")
    else:
        print("The given Matrix is Not Orthogonal Matrix")
    if(A@A==A).all():
        print("The given Matrix Idempotent Matrix")
    else:
        print("The given Matrix Not Idempotent Matrix")

In [37]:
properties(A)

The given Matrix is 
 [[1 0 1]
 [1 1 0]
 [0 2 1]]
The Determinant of The Matrix is  3
The Rank of the Matrix is:  3
The given Matrix is Square Matrix
The given Matrix is not Symmetric Matrix
The given Matrix is singular  Matrix
The given Matrix is Not Orthogonal Matrix
The given Matrix Not Idempotent Matrix
