In [2]:
import pandas as pd
import numpy as np

In [3]:
data={"name": ["manoj","xyz","sundar","deepika"],"age" : [22,23,22,24],"qualification":[15,15,14,12]}
data
df=pd.DataFrame(data)
df.insert(2,"Gender",["Male","Female","Male","Female"])
print(df)

      name  age  Gender  qualification
0    manoj   22    Male             15
1      xyz   23  Female             15
2   sundar   22    Male             14
3  deepika   24  Female             12


In [4]:
df.Gender

0      Male
1    Female
2      Male
3    Female
Name: Gender, dtype: object

In [5]:
df.replace(inplace=True)

In [6]:
df

name  age  Gender  qualification
0    manoj   22    Male             15
1      xyz   23  Female             15
2   sundar   22    Male             14
3  deepika   24  Female             12

In [7]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
df["Gender"]=LE.fit_transform(df.Gender)

In [16]:
df

name  age  Gender  qualification
0    manoj   22       1             15
1      xyz   23       0             15
2   sundar   22       1             14
3  deepika   24       0             12

In [17]:
df.rename(columns={"age":"vay"})

name  vay  Gender  qualification
0    manoj   22       1             15
1      xyz   23       0             15
2   sundar   22       1             14
3  deepika   24       0             12

In [21]:
# df.rename(index={0:"kareena"})

In [19]:
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [120]:
df["Gender"]=array

In [121]:
df

name  age  Gender  qualification
0    manoj   22       1             15
1      xyz   23       2             15
2   sundar   22       3             14
3  deepika   24       4             12

In [122]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [123]:
numpy_array=df.to_numpy()
print(numpy_array)


[['manoj' 22 1 15]
 ['xyz' 23 2 15]
 ['sundar' 22 3 14]
 ['deepika' 24 4 12]]


In [73]:
array_1=array.reshape(2,1)
display(array_1)

array([[1],
       [2]])

## Reshape

In [14]:
zw=np.arange(1,10)
display(zw)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
array_1=np.array([[1,2,2], [3,4,4]])
display(array_1)
array_1.reshape(-1)

array([[1, 2, 2],
       [3, 4, 4]])

array([1, 2, 2, 3, 4, 4])

In [16]:
array_1.reshape(2,3)

array([[1, 2, 2],
       [3, 4, 4]])

In [17]:
np.reshape(zw,(3,3),order='C')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.reshape(zw,(3,3),order='F')

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
np.reshape(zw,(3,3),order='A')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Resize

In [46]:
xw=np.arange(1,10)
display(xw)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.resize(xw,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.resize(xw,(5,5))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2],
       [3, 4, 5, 6, 7]])

In [60]:
xw.resize((5,5))

In [62]:
xw

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#dataset.loc[:,"Gender"]

# dataset.loc[:,["Gender","Age"]]

# dataset.iloc[:,[2,3]]

# display(dataset.iloc[:,3])
# print(dataset.iloc[:,3].ndim)

# display(dataset.iloc[:,[3]])
# print(dataset.iloc[:,[3]].ndim)