## Cramer's Rule

1. Solve the following systems of linear equations using Cramer’s rule.


(a) 2x1 − x2 + x3 = −3,x1 + x2 −3x3 = 17, 5x1 −2x2 −4x3 = 20

(b) 2x1 +3x2 − x3 = 4,x1 +4x2 + x3 = −1, 5x1 − x2 +2x3 = 1

(c) −x1 +2x2 +4x3 −2x4 +3x5 = 24, 20x1 +5x2 +3x3 −2x4 − x5 = 29,2x1 +18x2 +60x3 +5x4 −3x5 = 177, 2x1 +4x2 +4x3 +3x5 = 26

(d) 2x1 +3x2 − x3 = 4, x1 +4x2 + x3 = −1, 5x1 − x2 +2x3 = 1, 2x1 +3x2−6x3 +5x4 +4x5 = 0

In [18]:
import numpy as np
def Cramer(A,b):
    import numpy as np
    d=np.linalg.det(A)
    if(d!=0):
        row,col=A.shape
        x=[]
        for i in range(col):  
            C=A.copy()
            C[:,i]=b
            v=np.linalg.det(C)/np.linalg.det(A)
            x.append(round(v))
        print("The solution of the S.O.E. is:")
        print(x)
    else:
        print("The System has no solution")

In [19]:
#a)
A=np.matrix("2,-1,1;1,1,-3;5,-2,-4")
b=np.matrix("-3,17,20").transpose()
Cramer(A,b)

The solution of the S.O.E. is:
[2, 3, -4]


In [20]:
#b)
A=np.matrix("2,3,-1;1,4,1;5,-1,2")
b=np.matrix("4,-1,1").transpose()
Cramer(A,b)

The solution of the S.O.E. is:
[1, 0, -2]


In [25]:
#c)
A=np.matrix("-1,2,4,-2,3;20,5,3,-2,-1;2,18,60,5,-3;2,4,4,0,3;2,3,-6,5,4")
b=np.matrix("24,29,177,26,0").transpose()
Cramer(A,b)

The solution of the S.O.E. is:
[2, -3, 4, 1, 6]


## g-Inverse of the Non Full Rank Matrix

In [33]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
A=np.matrix("1,2,3;4,5,6;7,8,9")
r=np.linalg.matrix_rank(A)
print("Rank of the matrix is: ",r)
m,n=A.shape
G=np.zeros((m,n))
B=A[np.ix_([0,r],[0,r])]
r1=np.linalg.matrix_rank(B)
if(r==r1):
    G[np.ix_([0,r],[0,r])]=np.linalg.inv(B).T
    G=G.T
print("The g-Inverse of the Matrix is:\n" ,np.round(G))

Rank of the matrix is:  2
The g-Inverse of the Matrix is:
 [[-1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0. -0.]]


# Verify the Properties of the g_Inverse

In [36]:
#AGA=A
if(np.round(A@G@A)).any():
    print("Property Satisfied")
else:
    print("Property Not Satisfied")

Property Satisfied


In [37]:
#trace(AG)=trace(GA)=rank(A)
if np.trace(A@G)==round(np.trace(G@A))==np.linalg.matrix_rank(A):
    print("Property Satisfied")
else:
    print("Property not Satisfied")

Property not Satisfied


In [38]:
A=np.random.randint(1,9,(3,3))
print(A)

[[5 6 7]
 [1 2 3]
 [4 7 2]]


# Properties of matrix

In [39]:
def Properties(A):
    row,col=A.shape
    print("The given Matrix is \n",A)
    print("The Determinant Of the Matrix is",round(np.linalg.det(A)))
    print("The Rank of the Matrix is: ",np.linalg.matrix_rank(A ))
    if row==col:
        print("The given Matrix is Square Matrix")
    else:
        print("The given Matrix is Not Square Matrix")
    
    if (A.T==A).all():
        print("The given Matrix is Symmetric Matrix")
    else:
        print("The given Matrix is Not Symmetric Matrix")
    if (np.linalg.det(A)!=0).all():
        print("The given Matrix is Not Singular Matrix")
    else:
        print("The given Matrix is Non Singular Matrix")
    if (np.linalg.inv(A)==A.T).all():
        print("The given Matrix is Orthogonal Matrix")
    else:
        print("The given Matrix is Not Orthogonal Matrix")
    if (A@A==A).all():
        print("The given Matrix is Idempotent Matrix")
    else:
        print("The given Matrix is Not Idempotent Matrix")
        

In [40]:
Properties(A)

The given Matrix is 
 [[5 6 7]
 [1 2 3]
 [4 7 2]]
The Determinant Of the Matrix is -32
The Rank of the Matrix is:  3
The given Matrix is Square Matrix
The given Matrix is Not Symmetric Matrix
The given Matrix is Not Singular Matrix
The given Matrix is Not Orthogonal Matrix
The given Matrix is Not Idempotent Matrix


# Solution Of Systems Of Linear Equations

In [41]:
import numpy as np
A=np.matrix("2,-1,1;1,1,-3;5,-2,-4")
A1=np.matrix("1,2,3;4,5,6;7,8,9")
b=np.matrix("-3,17,20").transpose()
print(round(np.linalg.det(A1)))
print(round(np.linalg.det(A)))

0
-16


In [43]:
def SLE(A,b):
    if round(np.linalg.det(A))==0:
        r=np.linalg.matrix_rank(A)
        print("Rank of the matrix is: ",r)
        m,n=A.shape
        G=np.zeros((m,n))
        B=A[np.ix_([0,r],[0,r])]
        r1=np.linalg.matrix_rank(B)
        if(r==r1):
            G[np.ix_([0,r],[0,r])]=np.linalg.inv(B).T
            G=G.T
        print("The g-Inverse of the Matrix is:\n" ,G)
        print("\nThe System has Infinite solutions")
        z1=np.random.rand(n,1)*10
        z2=np.random.rand(n,1)*10
        I=np.eye(n)
        print("first solution of SLE:\n",np.round(G*b+(I-G*A)*z1))
        print("Second solution of SLE:\n",np.round(G*b+(I-G*A)*z2))
    else:
        Inv=np.linalg.inv(A)
        #AX=b
        #X=inv(A)*b
        s=np.linalg.inv(A)*b
        print("The unique solution of  SLE is\n:",np.round(s))
        

In [44]:
SLE(A,b)

The unique solution of  SLE is
: [[ 2.]
 [ 3.]
 [-4.]]


In [45]:
SLE(A1,b)

Rank of the matrix is:  2
The g-Inverse of the Matrix is:
 [[-0.75        0.          0.25      ]
 [ 0.          0.          0.        ]
 [ 0.58333333  0.         -0.08333333]]

The System has Infinite solutions
first solution of SLE:
 [[ 3.]
 [ 9.]
 [-8.]]
Second solution of SLE:
 [[ 7.]
 [ 1.]
 [-4.]]


# Using Spectral Decomposition Find the Power of the matrix

In [4]:
import numpy as np
A=np.array([[3,-1,1],[-1,5,-1],[1,-1,3]])
P,L=np.linalg.eig(A)
E=np.diagflat(np.linalg.eigvals(A))
print(E)

[[6. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


or

In [5]:
E=np.diag(list(np.linalg.eigvals(A)))
print(E)

[[6. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [6]:
def SDT_Power(A,c):
    import numpy as np
    P,L=np.linalg.eig(A)
    E=np.diag(list(np.linalg.eigvals(A)))
    return np.round(L@E**c@L.T)
SDT_Power(A,2) #A^2

array([[11., -9.,  7.],
       [-9., 27., -9.],
       [ 7., -9., 11.]])

In [7]:
SDT_Power(A,7) #A^7

array([[ 47449., -92583.,  47321.],
       [-92583., 187353., -92583.],
       [ 47321., -92583.,  47449.]])

In [8]:
SDT_Power(A,1/2) #A^0.5

array([[ 2., -0.,  0.],
       [-0.,  2., -0.],
       [ 0., -0.,  2.]])

In [9]:
SDT_Power(A,3/2) #A^1.5

array([[ 6., -3.,  3.],
       [-3., 12., -3.],
       [ 3., -3.,  6.]])

# GSO(Gram_Smith_Orthogonalization)

In [10]:
x1=np.array([3,1,-1,3])
x2=np.array([-5,1,5,-7])
x3=np.array([1,1,-2,8])

In [11]:
import numpy as np

def GSO3(x1,x2,x3):
    import pandas as pd
    import numpy as np
    z1=x1
    z2=x2-(np.inner(x2,z1)/np.inner(z1,z1)*z1)
    z3=x3-(np.inner(x3,z1)/np.inner(z1,z1)*z1)-(np.inner(x3,z2)/np.inner(z2,z2)*z2)
    
    print("Orthogonal:\n",z1,z2,z3,"\nOrthonormal\n:",z1/np.linalg.norm(z1),z2/np.linalg.norm(z2),z3/np.linalg.norm(z3))
    

In [12]:
GSO3(x1,x2,x3)

Orthogonal:
 [ 3  1 -1  3] [ 1.  3.  3. -1.] [-3.  1.  1.  3.] 
Orthonormal
: [ 0.67082039  0.2236068  -0.2236068   0.67082039] [ 0.2236068   0.67082039  0.67082039 -0.2236068 ] [-0.67082039  0.2236068   0.2236068   0.67082039]


In [13]:
np.random.seed(1)
x=np.random.randint(0,2,(4,4))
print(x)

[[1 1 0 0]
 [1 1 1 1]
 [1 0 0 1]
 [0 1 1 0]]


In [14]:
x1=x[:,0]
x2=x[:,1]
x3=x[:,2]
x4=x[:,3]


In [15]:
def GSO4(x1,x2,x3,x4):
    import pandas as pd
    import numpy as np
    z1=x1
    z2=x2-(np.inner(x2,z1)/np.inner(z1,z1)*z1)
    z3=x3-(np.inner(x3,z1)/np.inner(z1,z1)*z1)-(np.inner(x3,z2)/np.inner(z2,z2)*z2)
    z4=x4-(np.inner(x4,z1)/np.inner(z1,z1)*z1)-(np.inner(x4,z2)/np.inner(z2,z2)*z2)-(np.inner(x4,z3)/np.inner(z3,z3)*z3)
    l=[np.round(z1),np.round(z2),np.round(z3),np.round(z4)]
    l1=[z1/np.linalg.norm(z1),z2/np.linalg.norm(z2),z3/np.linalg.norm(z3),z4/np.linalg.norm(z4)]
    l2=[]
    for i in l1:
        l2.append(np.round(i))
    print("Orthogonal: \n",l,"\nOrthonormal: \n",l2)

In [16]:
GSO4(x1,x2,x3,x4)

Orthogonal: 
 [array([1, 1, 1, 0]), array([ 0.,  0., -1.,  1.]), array([-1.,  0.,  0.,  0.]), array([ 0., -0., -0.,  0.])] 
Orthonormal: 
 [array([1., 1., 1., 0.]), array([ 0.,  0., -1.,  1.]), array([-1.,  1.,  0.,  0.]), array([ 1., -0., -0.,  0.])]


# Obtain an 4 by 4 orthogonal matrix with all elements in first row equal

In [17]:
x4=[1, 1, 1, 1]
x3=[0, 1, -1, 1]
x2=[-1, 0, 1, 1]
x1=[1, 0, 1, 1]
z1=x1/np.linalg.norm(x1)
z2=x2/np.linalg.norm(x2)
z3=x3/np.linalg.norm(x3)
z4=x4/np.linalg.norm(x4)
np.array([z1,z2,z3,z4])

array([[ 0.57735027,  0.        ,  0.57735027,  0.57735027],
       [-0.57735027,  0.        ,  0.57735027,  0.57735027],
       [ 0.        ,  0.57735027, -0.57735027,  0.57735027],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ]])

In [18]:
y1=z4
y2=x3-np.inner(x4,y1)/np.inner(y1,y1)*z4
y3=x2-np.inner(x2,y2)/np.inner(y2,y2)*y2-np.inner(x2,y1)/np.inner(y1,y1)*y1
y4=x1-np.inner(x1,y1)/np.inner(y1,y1)*y1-np.inner(x1,y2)/np.inner(y2,y2)*y2-np.inner(x1,y3)/np.inner(y3,y3)*y3
np.array([y1,y2,y3,y4])

array([[ 0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [-1.        ,  0.        , -2.        ,  0.        ],
       [-1.45      , -0.25      ,  0.35      ,  0.75      ],
       [-0.52807018, -0.78070175, -0.90701754,  0.34210526]])